* Details
  Improvise comes with the following library packages installed:

  - kernel, 1.0.7 (#2) Kernel Package
  - primitive, 0.0.2 (#20) Primitive Package
  - persistent, 0.0.1 (#35) Persistent Package
  - dialog, 0.0.3 (#39) Dialog, Web Server Package
  - dialog_extras, 0.0.2 (#49) Dialog, Extras
  - mustache, 0.0.1 (#54) Mustache Templating Language Package
  - identity, 0.0.1 (#58) Identity Package
  - player, 0.0.1 (#62) Player Package

  And a starter package:

  - application, 0.0.2 (#69) Application Package

* FAQ
** How do I log in?
   See "How do I start the web server?" below for web-based access,
   otherwise...  Passkeys for the two built-in players/users are
   output to the console when the server loads the database.  Look for
   lines that begin with ~PASSKEY for ...~.  The passkey is the long
   hexadecimal string.  The server starts listening on port 7777 by
   default.  Using telnet, connect to the running server and type
   ~connect~ followed by the hexadecimal string.  Ex:
   #+BEGIN_EXAMPLE
   connect D210CA62C37E841CD6936146A9768EA9246D3A7917EDE3BFC1A29C63C058F783
   #+END_EXAMPLE
   If successful, you'll be greeted by the string ~*** Connected ***~.

** How do I see which packages are installed?
   Once logged in type:
   #+BEGIN_EXAMPLE
   @list packages with $composed
   #+END_EXAMPLE
   ~$composed~ is the reference to the package manager.  The command output
   lists the packages that are installed, as well as additional packages
   available at [[http://stunt.io/][stunt.io]].

** How do I install new packages?
   Assuming package dependencies are met ("autoport" depends on the
   package "lambdacore" being installed first, for example), type the
   following:
   #+BEGIN_EXAMPLE
   @install <package> with $composed
   #+END_EXAMPLE

** How do I start the web server?
   Assuming the "dialog" package is installed (it is by default), type
   the following as a wizardly player:
   #+BEGIN_EXAMPLE
   ; #73:start(<port>)
   #+END_EXAMPLE
   ~#73~ is the object number of the HTTP server object built from the
   HTTP server prototype and a few objects from the "dialog_extras"
   package.  Stop the server with:
   #+BEGIN_EXAMPLE
   ; #73:stop()
   #+END_EXAMPLE
   Test the server by opening ~http://localhost:<port>/~ in a browser.
   You'll see the default home page.  You can connect to an existing
   user by typing their object number (not super-secure, I know).
   Once connected you can browse the database and send commands
   directly to the server.

* Check out
  The GitHub source:

  - [[https://github.com/toddsundsted/stunt][https://github.com/toddsundsted/stunt]]

  The Stunt site:

  - [[http://stunt.io][http://stunt.io]]
  - [[http://stunt.io/dated/hoisting-lambdacore][http://stunt.io/dated/hoisting-lambdacore]]
  - [[http://stunt.io/packages/primitive][http://stunt.io/packages/primitive]]
